AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Project | Bag Check Processor (SQS to DynamoDB)
Parameters:
  ProjectBagCheckTable:
    Type: String
    Default: project_checked_bags
Resources:
  BagProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Project_Bag_Processor_Function
      Runtime: python3.11
      Handler: src.app.handler
      CodeUri: ./
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          DDB_TABLE: !Ref ProjectBagCheckTable
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:577638382580:Project_Bag_Check_Queue
            BatchSize: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectBagCheckTable
